services:
  # Instancia de SQL Server (Optimizada para ARM64/Apple Silicon)
  sqlserver:
    image: "mcr.microsoft.com/azure-sql-edge:latest"
    container_name: ecommerce_sqlserver
    user: root
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong@Password123
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql/data

  # Instancia de Redis (Motor Clave-Valor en Memoria)
  redis:
    image: "redis:alpine"
    container_name: ecommerce_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  sqlserver_data:
  redis_data:
